# Generated by Django 4.0.5 on 2022-06-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_image',
            field=models.ImageField(default='default.jpg', upload_to='app_images'),
        ),
    ]
