# Generated by Django 4.0.5 on 2022-06-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='utility_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='utility_name',
            new_name='utility',
        ),
    ]
